#spring:
#  cloud:
#    gateway:
#      routes:
#        - id : customer-microservice
#          uri : http://localhost:8081
#          predicates :
#            - Path= /customers/**
#        - id : account-microservice
#          uri : http://localhost:8082
#          predicates:
#            - Path= /accounts/**
